
global.FONTS = ['Inter',
    'Work Sans',
    'Space Mono',
    'Space Grotesk',
    'Rubik',
    'Libre Franklin',
    'Cormorant',
    'Fira Sans',
    'Chivo',
    'Eczar',
    'Alegreya Sans',
    'Alegreya',
    'Source Sans Pro',
    'Source Serif Pro',
    'Roboto',
    'Roboto Slab',
    'BioRhyme',
    'Inknut Antiqua',
    'Poppins',
    'Archivo Narrow ',
    'Libre Baskerville',
    'Playfair Display',
    'Karla',
    'Lora',
    'Proza Libre',
    'Spectral',
    'IBM Plex Sans',
    'Crimson Text',
    'Montserrat',
    'Lato',
    'PT Sans ',
    'PT Serif',
    'Cardo ',
    'Neuton',
    'Open Sans',
    'Inconsolata',
    'Cabin',
    'Raleway', 
    'Anonymous Pro', 
    'Merriweather' 
];